import React from "react";
import { AbsoluteFill, Audio, Sequence, staticFile } from "remotion";
import { Intro } from "./scenes/Intro";
import { Problem } from "./scenes/Problem";
import { DidExplain } from "./scenes/DidExplain";
import { VcExplain } from "./scenes/VcExplain";
import { Trust } from "./scenes/Trust";
import { Outro } from "./scenes/Outro";
import { BrandWatermark } from "./components/BrandWatermark";

export const FPS = 30;

// Scene timing (frames @ 30fps) — mirrors voiceover-script.md timestamps.
// `audio` maps each scene to its narration clip from voiceover-script.md
// (public/audio/line-0N.mp3, generated by scripts/generate-voiceover.mjs).
const SCENES = [
  { name: "Intro", from: 0, duration: 150, Comp: Intro, audio: "line-01.mp3" }, // 0:00-0:05
  { name: "Problem", from: 150, duration: 180, Comp: Problem, audio: "line-02.mp3" }, // 0:05-0:11
  { name: "DidExplain", from: 330, duration: 210, Comp: DidExplain, audio: "line-03.mp3" }, // 0:11-0:18
  { name: "VcExplain", from: 540, duration: 210, Comp: VcExplain, audio: "line-04.mp3" }, // 0:18-0:25
  { name: "Trust", from: 750, duration: 150, Comp: Trust, audio: "line-05.mp3" }, // 0:25-0:30
  { name: "Outro", from: 900, duration: 90, Comp: Outro, audio: "line-06.mp3" }, // 0:30-0:33
];

export const TOTAL_DURATION_FRAMES = SCENES.reduce(
  (max, s) => Math.max(max, s.from + s.duration),
  0
);

export const DIDExplainer: React.FC = () => {
  return (
    <AbsoluteFill style={{ backgroundColor: "#0A0A1E" }}>
      {SCENES.map(({ name, from, duration, Comp, audio }) => (
        <Sequence key={name} name={name} from={from} durationInFrames={duration}>
          <Comp />
          <Audio src={staticFile(`audio/${audio}`)} />
        </Sequence>
      ))}
      <BrandWatermark />
    </AbsoluteFill>
  );
};
