import React from "react";
import { AbsoluteFill, Audio, staticFile } from "remotion";
import { TransitionSeries, linearTiming } from "@remotion/transitions";
import { fade } from "@remotion/transitions/fade";
import { Intro } from "./scenes/Intro";
import { Problem } from "./scenes/Problem";
import { DidExplain } from "./scenes/DidExplain";
import { VcExplain } from "./scenes/VcExplain";
import { Trust } from "./scenes/Trust";
import { Outro } from "./scenes/Outro";
import { BrandWatermark } from "./components/BrandWatermark";

export const FPS = 30;

// Frames each scene crossfades into the next — replaces the old hard Sequence
// cuts (DUTA-1164 revision after board feedback: cuts felt too abrupt).
const TRANSITION_FRAMES = 16;

// Per-scene duration (frames @ 30fps). Each scene now runs longer than its
// narration clip so the on-screen diagram/animation has room to finish
// playing and settle before the crossfade starts, instead of getting cut off
// the instant the voice line ends.
// `audio` maps each scene to its narration clip from voiceover-script.md
// (public/audio/line-0N.mp3, generated by scripts/generate-voiceover.mjs).
const SCENES = [
  { name: "Intro", duration: 170, Comp: Intro, audio: "line-01.mp3" }, // VO ~5s
  { name: "Problem", duration: 200, Comp: Problem, audio: "line-02.mp3" }, // VO ~6s
  { name: "DidExplain", duration: 260, Comp: DidExplain, audio: "line-03.mp3" }, // VO ~7s
  { name: "VcExplain", duration: 260, Comp: VcExplain, audio: "line-04.mp3" }, // VO ~7s
  { name: "Trust", duration: 280, Comp: Trust, audio: "line-05.mp3" }, // VO ~5s, recap diagram + headline
  { name: "Outro", duration: 150, Comp: Outro, audio: "line-06.mp3" }, // VO ~3s
];

export const TOTAL_DURATION_FRAMES =
  SCENES.reduce((sum, s) => sum + s.duration, 0) -
  TRANSITION_FRAMES * (SCENES.length - 1);

export const DIDExplainer: React.FC = () => {
  return (
    <AbsoluteFill style={{ backgroundColor: "#0A0A1E" }}>
      <TransitionSeries>
        {SCENES.map(({ name, duration, Comp, audio }, i) => (
          <React.Fragment key={name}>
            <TransitionSeries.Sequence name={name} durationInFrames={duration}>
              <Comp />
              <Audio src={staticFile(`audio/${audio}`)} />
            </TransitionSeries.Sequence>
            {i < SCENES.length - 1 && (
              <TransitionSeries.Transition
                presentation={fade()}
                timing={linearTiming({ durationInFrames: TRANSITION_FRAMES })}
              />
            )}
          </React.Fragment>
        ))}
      </TransitionSeries>
      <BrandWatermark />
    </AbsoluteFill>
  );
};
